### ISSUE TITLE
infinite scroll for <!--nextpage--> 

### ISSUE THREAD

**Issue by PhilScalableGroup** [dcooney/wordpress-ajax-load-more#102]
I am looking to do an infinite scroll within a single post where the wordpress nextpage shortcode() is used.  

Instead of having pagination on the post for each section of the post I would like for there to be an infinite scroll of the sections of the post.

Is this something that this plugin can do?

https://codex.wordpress.org/Styling_Page-Links
https://codex.wordpress.org/Function_Reference/wp_link_pages
https://codex.wordpress.org/Write_Post_SubPanel#Quicktags

**Comment by dcooney** [comment]
No sorry - link pages are not supported.
