### ISSUE TITLE
Custom counters

### ISSUE THREAD

**Issue by cjhmdm** [dcooney/wordpress-ajax-load-more#103]
Hello,
Would it be possible to add support for custom counters that reset on each "page" load?

for instance, a simple counter like this:

`<?php 
  $i=0; while (have_posts() ) : the_post();
    // do stuff
  $i++; endwhile;
?>
`

Now, I know you provide the $alm_item counter, but this doesn't reset when a new "page" of content is loaded, which makes it almost impossible to make layout modifications based on the counter.

**Comment by dcooney** [comment]
There is a another variable that is not documented.
```$alm_loop_count;```

That will get you the current item in that single query.

**Comment by cjhmdm** [comment]
Thanks dcooney, but this variable returns empty for me.

**Comment by dcooney** [comment]
Really? I just tested it on my development site...
What version of the plugin are you using?

**Comment by cjhmdm** [comment]
The latest from the wordpress depo.

I'm looking through ajax-load-more.php and at first glance (I just now started looking) and it appears as though the var $alm_loop_count is only set when using "preload".

**Comment by dcooney** [comment]
$alm_loop_count is set on line 1029 of ajax-load-more.php

**Comment by cjhmdm** [comment]
Right, I see that now: $alm_loop_count = 0;

Strange that it's not returning anything for me. I doubt that it matters but I'm attempting to call the variable from within my theme repeater file.

**Comment by dcooney** [comment]
Oh, that makes sense then. It's not passing $alm_loop_count through the do_action to the theme repeater.

I'll add this to my list of fixes for the next release.

**Comment by cjhmdm** [comment]
Ok, seems that it does matter. I get the expected return when using the standard repeaters, but not when using the theme repeaters.

Just saw your update, I'll keep an eye out for the update. In the meantime, I'll use the standard repeaters.

Thanks dcooney

**Comment by dcooney** [comment]
In Ajax Load More 2.9 `$alm_current` is available. This resets after every query so you can target a specific post number with each loop.
