### ISSUE TITLE
Add option to set no container type

### ISSUE THREAD

**Issue by cjhmdm** [dcooney/wordpress-ajax-load-more#104]
Hello again,

Would it be possible to add an option to set no container type as opposed to only div or ul?

Reason being is those containers can (and do) interfere with other layout/styling options. In my specific case, I have the page setup to show 1 "large" post (full size), followed by 2 "small" posts (half size) that should be side by side (using foundations grid system), followed by another "large" post (full size).

The problem is, the foundation grid, in this case, breaks due to the container.

**Comment by cjhmdm** [comment]
Doing some playing around, it seems that setting container_type="" in the shortcode does as I'm intending. Perhaps make this option available in the settings as well for ease of use?

**Comment by dcooney** [comment]
That might work, it will produce invalid HTML.
The plugin requires a container_type because JS functions are triggered based on the container classes.
