### ISSUE TITLE
Posts per page issue

### ISSUE THREAD

**Issue by cjhmdm** [dcooney/wordpress-ajax-load-more#105]
Hello again,

I'm working from the "index" file in this particular instance. 

I'm loading some static content at the top of the page, followed by a small custom loop for displaying some thumbs, then using your plugin to load all of the actual posts below that. 

I've tried to reset the custom loop for thumbs using both wp_reset_postdata and wp_reset_query, as well as remove this loop altogether, but no matter what, the initial set of posts loaded by your plugin, always uses the value defined in "reading settings" and ignores the shortcode value set.

After the initial set of posts is loaded however, the correct number of posts as defined in the shortcode are loaded for each "page" thereafter, so it's only an issue with the very first set loaded.

**Comment by cjhmdm** [comment]
Just did some testing, and even when setting up an initial loop, the calling more posts via your plugin and using offsets, the plugin continues to ignore the posts_per_page option in the shortcode and always loads the value set in the "reading settings" for the initial query (which in my case is the default 10)

**Comment by dcooney** [comment]
Never heard of this one before.
Can you confirm ajax_load-more shortcode is outside your index loop.

**Comment by cjhmdm** [comment]
Yep, I can confirm the shortcode is not inside any loop. In fact, the only loop I'm actively using on the page is in the form of "WP_Query", which I've also removed completely to make sure it wasn't that causing it.

**Comment by dcooney** [comment]
Are you using the SEO add-on?

If not, I have no idea why this is happening, sorry.

**Comment by cjhmdm** [comment]
I am indeed using the SEO add-on

**Comment by dcooney** [comment]
Please read this section in the docs.
https://connekthq.com/plugins/ajax-load-more/add-ons/search-engine-optimization/#postsperpage

**Comment by cjhmdm** [comment]
Yep, I saw already. I've gotten out of the habit of reading docs anymore, so my apologies there.

**Comment by dcooney** [comment]
No worries... closing.

**Comment by sabbirshawon** [comment]
I use in wp_query posts per page = 5; but in ajax load it loads only 5 post with same post repeater. how to fix it?
