### ISSUE TITLE
Feature Request: add RAND to orderby

### ISSUE THREAD

**Issue by cjhmdm** [dcooney/wordpress-ajax-load-more#106]
Would it be possible to add the rand filter for orderby like the standard wp query args allow?

I know there's a "random" filter in your "order" options (not currently in the shortcode builder but is listed in the docs), but as you already know, this filter doesn't currently work; so I was thinking that adding it to the "orderby" parameter instead of trying to add it to the "order" parameter might solve the issue you're having.

**Comment by dcooney** [comment]
Closing ticket as ordering by Rand will not be supported.
