### ISSUE TITLE
Ajax-load-more order by random not working

### ISSUE THREAD

**Issue by johny90** [dcooney/wordpress-ajax-load-more#108]
I am using plugin Version 2.8.5, the sorting for random and comment count is not working. How can I fix it? Here's the shortcode i used: 
[ajax_load_more post_type="post" category="places-to-go" posts_per_page="9" scroll="false" button_label="LOAD MORE" container_type="div" orderby="random"]

**Comment by dcooney** [comment]
Ordering by random is not supported by the plugin, however `orderby="comment_count"` should be working as it is supported by wp_query.

Also, FYI - in your code it should be `orderby="rand"` not random.

**Comment by johny90** [comment]
Thanks, the problem solved.
