### ISSUE TITLE
Is it possible to set include_children to false in a shortcode?

### ISSUE THREAD

**Issue by KoenRijpstra** [dcooney/wordpress-ajax-load-more#109]
```include_children (boolean) - Whether or not to include children for hierarchical taxonomies. Defaults to true.```

https://codex.wordpress.org/Class_Reference/WP_Query

**Comment by dcooney** [comment]
That is not part of the available params.
If you need this, you could always use the filter alm_modify_query_args()
https://connekthq.com/plugins/ajax-load-more/docs/filter-hooks/#alm_query_args
