### ISSUE TITLE
error with custom taxonomy and custom post

### ISSUE THREAD

**Issue by jorge-vitrubio** [dcooney/wordpress-ajax-load-more#110]
I have to go back on line 529 to old code
_the original code_
`// ALM Wrapper`
`$ajaxloadmore .= '<div id="ajax-load-more" class="ajax-load-more-wrap'. $btn_color .''. $paging_color .''. $alm_layouts .'" data-id="" data-canonical-url="'. $canonicalURL .'" data-slug="'. $slug .'">';`

_replaced by this one_
`$ajaxloadmore .= '<div id="ajax-load-more" class="ajax-load-more-wrap'. $btn_color .''. $paging_color .''. $alm_layouts .'" data-id="" data-canonical-url="'.get_permalink().'" data-slug="'. $post->post_name .'">';
`

I have custom post type and custom taxonomy and it is throwing some error when displaying the mentioned custom category and custom taxonomy archive pages, but not the other entries, pages, or even woocommerce. 

I have changed on line 529. Replacing with 2016/02/23 backup that i had it is working ok.

The error appeared on the last update, It might be my error but please, feel free to check.

thanks again for your plugging, it is great.

**Comment by dcooney** [comment]
Do you recall what the error was?
I changed by the data-canonical-url and data-slug with the last release.
