### ISSUE TITLE
Polylang issue

### ISSUE THREAD

**Issue by SunfishTobbe** [dcooney/wordpress-ajax-load-more#112]
If you have Polylang activated but haven't activated language support on the specific post_type you are fetching, you will get a null result.

I suggest changing

```
if (function_exists('pll_current_language')) // Polylang - https://wordpress.org/plugins/polylang/
    $lang = pll_current_language();
```

to

```
if (function_exists('pll_current_language')) { // Polylang - https://wordpress.org/plugins/polylang/
    if ( pll_is_translated_post_type($post_type) )
        $lang = pll_current_language();
    else
        $lang = '';
}
```

Note: This won't work if $post_type is a comma separated list but maybe you have a solution for that.

**Comment by dcooney** [comment]
Thanks... I'll have a look at this.
