### ISSUE TITLE
MaterializeCSS+Masonry: Overlapping occurring even with imagesLoaded js

### ISSUE THREAD

**Issue by kingIZZZY** [dcooney/wordpress-ajax-load-more#114]
http://dev.randompod.com

Trying to use MaterializeCSS (known css library) with masonry as templated/exemplified here: https://github.com/Dogfalo/materialize/tree/master/templates/masonry-template

Masonry isn't working well; grid items are overlapping despite running the code as advised at https://connekthq.com/plugins/ajax-load-more/examples/masonry/#javascript including masonry and imagesLoaded javascript

Source: http://dev.randompod.com/wp-content/themes/dev/js/app.js

**Comment by kingIZZZY** [comment]
Also - why is the [Masonry Example JS snippet](https://connekthq.com/plugins/ajax-load-more/examples/masonry/#javascript) showing to call `imagesLoaded()` which I'm _guessing_ is referring to the imagedLoaded() JS library/plugin - when in fact ajax-load-more.js seems to embed [its own waiting for images solution ](https://github.com/dcooney/wordpress-ajax-load-more/blob/ff076ad79f4f0b4d8ddb4ef842d1895457db71db/core/js/ajax-load-more.js#L1298) apparently based on https://github.com/alexanderdickson/waitForImages !

Either way - apparently even with both plugins there's still some overlapping / layout quirks, see the test case http://dev.randompod.com

**Comment by dcooney** [comment]
> why is the Masonry Example JS snippet showing to call imagesLoaded() which I'm guessing is referring to the imagedLoaded() JS library/plugin?
Simply because Masonry doesn't care about the ALM version of Wait for Images.

You layout is fine if you resize your browser, so the issue is the timing and loading of the posts.
It's as though Masonry is being triggered before the posts have been added to the page.
Have you tried using imagesLoaded? It might provide the delay needed to fix the issue.
Or even try using a setTimeout on the masonry call. https://codeshare.io/fpywQ

**Comment by kingIZZZY** [comment]
Thank you for the reply!

> Simply because Masonry doesn't care about the ALM version of Wait for Images.

1) Even if so, the fact that masonry is being refreshed upon waitForImages completion it still should workm and 2) How then does the Ajax Load More plugin officially suggest to implement the masonry example, imagesLoaded or waitForImages, if as you claim Masonry "doesn't care" about them?

Yes I noticed that triggering resize event does get masonry to re-layout everything, although even then the next loaded batch remains all overlapped into one...

I have actually tried all of the above; with imagesLoaded and with setTimeout. There's _still_ overlapping going on. I agree it seems like the timing/sequencing might be off, I tried to order all the scripts as best as possible, but between all the libraries/plugins being used here maybe there are some async callbacks which are out of control my to "sequence" correctly...

Let me put imagesLoaded() back in there (maybe with a URL parameter to enable/disable dynamically) and setTimeout() so you can see the problem still exists.

Thanks again!

**Comment by kingIZZZY** [comment]
Alright, I hope I hacked this mini testing "API" well, lemme know if anything doesn't test/work right. Set any of the following URL params:

- `images_loaded=1` - will set the images_loaded="true" ALM shortcode attribute, thus (i guess) using the ALM built-in waitForImages
- `imagesLoaded=1` - will make use of imagesLoaded plugin. Not to be confused with (and can be combined with) `images_loaded`
- `setTimeout=100` - will trigger almComplete masonry on a timeout of specified milliseconds. Keep in mind any timeout delay at all is undesirable in the website and ideally eliminated...
- `callmasonry1=1` or `callmasonry1=command` - cause additional call to masonry after `reloadItems` with specified string (ex. `layout`, or just `1` for no command)
- `callmasonry2=1` or `callmasonry2=command` - same as above for the async call to masonry within the setTimeout
- `callmasonry3=1` or `callmasonry3=command` - same as above for the extra non-async (immediate) call to masonry right after the async setTimeout one

**Comment by dcooney** [comment]
The example on the [website](http://connekthq.com/plugins/ajax-load-more/examples/masonry/) is fairly basic. 
Did you following this exactly? Even the shortcode params?

What version of ALM are you running?

**Comment by kingIZZZY** [comment]
ALM Version 2.11.1

The shortcode: `[ajax_load_more post_type="post" posts_per_page="10" max_pages="0"]`
Tried with & without `images_loaded="true"` and `transition_container="false"`

Yes I basically copy-pasted the JS snippet from the masonry example. By now I messed around with the code quite a bit, but browsing http://dev.randompod.com/?imagesLoaded=1 to should have the exact effect as the [original snippet from the masonry page](https://connekthq.com/plugins/ajax-load-more/examples/masonry/#javascript). You can [view the code](http://dev.randompod.com/wp-content/themes/dev/js/app.js) (or even step through it in chrome inspector) to verify this.

**Comment by dcooney** [comment]
I'm out of ideas. I get 4-5 masonry support requests every week and haven't seen this issue before.
