### ISSUE TITLE
Feature request : Paging + Infinite Scroll + Cache

### ISSUE THREAD

**Issue by manuhook** [dcooney/wordpress-ajax-load-more#118]
Hello !

Paging + Infinite Scroll + Cache : works super fine together. 👍 

However when you leave the infinite scroll page and you hit the history back button to go back on this page it's making a big request never cached (specially if you try to load lot of post, example if the "page" > 20). 

Is it possible to cache this kind of request ?

Thank you,

**Comment by dcooney** [comment]
Hi manuhook,

> Is it possible to cache this kind of request ?

It's not, not yet anyways.... This is a known issue with the plugin that I have not been able to solve.

Caching will not work on initial page load if the request is for greater than a single page (i.e. /page/3)/. Caching will start to work for requests following that.

The issue I need to work out is how to served mixed requests, both cache and regular ajax requests if a user requests /page/15/ but only pages 1-10 have been cached. Or even more tricky would be, pages 1-5 and 11-15 have been cached, but 6-10 have not.

When cache is being served Ajax Load More never hits the server.

I have a few ideas I've been thinking about that may solve this, the most appropriate one might be to check that ALL pages have been cached, if so then serve them. If not, keep the standard implementation. 

Any thoughts?

**Comment by manuhook** [comment]
> I have a few ideas I've been thinking about that may solve this, the most appropriate one might be to check that ALL pages have been cached, if so then serve them. If not, keep the standard implementation.

Yes it's seems to be a pretty good idea, it's mean if everything is cached you will call each cached files page-0.html, page-1.html etc.. ? 

Maybe it's more easy for you to cache directly the result of a specified request : if someone is calling directly page the /page/15/ create a cached file like page-0-15.html with all the content from the page 0 to 15, and serve this page if it's already cached ?

Thank you for your help :)

**Comment by dcooney** [comment]
> create a cached file like page-0-15.html

I ❤️ that idea.

**Comment by dcooney** [comment]
@manuhook just an FYI that I have solved this issue and it will be released at some point next week along with Ajax Load More 2.14.0.

This was solved by using your idea of caching pages like `page-0-14.html `and `page-0-2.html` etc.

**Comment by manuhook** [comment]
Great thank you :)
