### ISSUE TITLE
Update post count on resize

### ISSUE THREAD

**Issue by MarthSantos** [dcooney/wordpress-ajax-load-more#122]
Is it possible to update the number of posts to be shown when the window resizes?
For example, the desktop version of the site shows 12 posts, the tablet version shows 6 posts and mobile shows 4 posts.

I tried using the [filter example](https://connekthq.com/plugins/ajax-load-more/examples/filtering/) on your site.

It works properly on reload but once you start to resize the browser, it adds additional posts instead of reloading the post to get the new post count.

**Comment by dcooney** [comment]
@MarthSantos 
I'd suggest using a library such as http://mobiledetect.net/ to detect the device then update the `posts_per_page` based on that.

Let me know if that helps at all.

**Comment by MarthSantos** [comment]
@dcooney 
I just realized that I didn't mentioned that the post count is different when on iPad landscape(12 posts) and iPad portrait(6 posts).

So mobiledetect won't work for me. Do you have a function that I can use to reload the posts again?

**Comment by MarthSantos** [comment]
@dcooney 
I have managed to finally make it to work. I forgot to add a flag during resize.
Thanks for the suggestion. It might be useful in the future. :)
