### ISSUE TITLE
Feature request : Paging + Infinite Scroll : Scroll to top option

### ISSUE THREAD

**Issue by manuhook** [dcooney/wordpress-ajax-load-more#123]
Hi !

It will be great to have the possibilty to enable the the "Scroll to page" only when the full/entire page is loaded in the browser.

Like most of the website are now responsive, each time a new wordpress page is loaded in ajax, we have a différent "scrolling distance" depending the resolution of your screen and it's quite difficult to adjust the "Scoll Top" option dynamically.

Hope you understand what i try to explain :)

Thanks a lot :)

**Comment by dcooney** [comment]
Not a bad idea.
