### ISSUE TITLE
Hard dependency of WP jQuery not necessary if jQuery is included elsewhere

### ISSUE THREAD

**Issue by AustinBurns** [dcooney/wordpress-ajax-load-more#125]
Hello,

Loving the plugin, but I just have one big grip with it, and that is the fact that there is a hard dependency of the WP jQuery which is unnecessary for devs that have it bundled up in a js min file from Gulp or another task runner.

I understand that for most cases it would be fine since most people are not going to be minifying there own JS files together, but for those select few, I propose a solution to this problem being to add a filter right before the register call as so:

```
if( $dependencies = apply_filters( 'alm_js_dependencies', 'jquery' ) != '' ) {
       $dependencies = array($dependencies);
}
   		
// Load JS   		   		
//wp_register_script( 'ajax-load-more', plugins_url( '/core/js/ajax-load-more.js', __FILE__ ), $dependencies,  ALM_VERSION, true );
wp_register_script( 'ajax-load-more', plugins_url( '/core/js/ajax-load-more.min.js', __FILE__ ), $dependencies,  ALM_VERSION, true );  
```

Not only will that allow advanced devs to negate the hard WP jQuery dependency, but that will also allow others to add dependencies for whatever reason if they absolutely need to (although I am not sure there would really be an actual case for this.)

Also, this will keep the option out of the Admin UI so novice devs will not accidentally turn off the dependency and therefore have a broken plugin.

What do you think?

Let me know and if you want I can make a pull request and add the code in myself so you don't have to do any work :)

**Comment by dcooney** [comment]
@AustinBurns I like this. I'm been thinking about this for quite some time actually. I'll add this in to a future release.

**Comment by dcooney** [comment]
@AustinBurns Im looking at adding this feature. 
What does your filter look like to disable the dependency?

**Comment by AustinBurns** [comment]
@dcooney,

This is how I currently have it disabled on the site I am working on.

```
if ( ! function_exists( 'remove_jquery_dependency' ) ) {
	function remove_jquery_dependency($dependencies) {
		return;
	}
}
add_filter('alm_js_dependencies', 'remove_jquery_dependency');
```

Let me know if you need help with anything.

**Comment by dcooney** [comment]
Ok cool.
Simplified a bit... would this work? 

```
// ajax-load-more.php
$dependencies = apply_filters( 'alm_js_dependencies', array('jquery') );
wp_register_script( 'ajax-load-more', plugins_url( '/core/js/ajax-load-more.min.js', __FILE__ ), $dependencies,  ALM_VERSION, true ); 
```

```
// functions.php
// Remove jQuery dependancy 
add_filter('alm_js_dependencies', '__return_false'); 
```

**Comment by AustinBurns** [comment]
From a quick test it does seem like that would work. I was just building it so that it could accomodate multiple dependencies in case the plugin calls for that in the future :)

**Comment by dcooney** [comment]
Ok great. Yea, I seen that.. but for simplicity I think i'll merge my example.

Thanks for contributing!
