### ISSUE TITLE
editorconfig / indention & trailing whitespaces

### ISSUE THREAD

**Issue by stroebjo** [dcooney/wordpress-ajax-load-more#128]
I noticed there a quite a few trailing spaces, also indention preference is not quite clear to me. 

Maybe add an `.editorconfig` to the project to reduce "change noise" as in commit wich only change indention/whitespace/etc.?

[EditorConfig](http://editorconfig.org/) can be used to set preferences for indention and whitespace handling to the projects wishes.

**Comment by dcooney** [comment]
Agree, driving me nuts.

**Comment by stroebjo** [comment]
Are you defining one or are you open to a pull request? Something like is is probably a good Idea: https://github.com/pfefferle/.editorconfigs/blob/master/php-psr-2/.editorconfig :)

**Comment by dcooney** [comment]
I'm going to add one to the new version i'm releasing this weekend. 
Im under the impression adding an editor config will NOT format what has already been coded?

True?

**Comment by stroebjo** [comment]
Yes, existing code will not be affected until you save/fix it.

But there are tools like [eclin](https://github.com/jedmao/eclint) which try to fix existing code according to the given `.editorconfig`. I have no  experience using it, but maybe it's worth a try?
