### ISSUE TITLE
Cache add-on is not working

### ISSUE THREAD

**Issue by skftn** [dcooney/wordpress-ajax-load-more#130]
Just bought the cache add-on, seems to be not working:

- Unzipped .zip in `wp-content/plugins`
- Activated plugin in wordpress admin
- Activated my license
- Ensured that my the `_cache` directory is writeable
- Modified my shortcode with `cache="true"` and `cache_id="1666392211"`

Visit my page, scroll down to generate some new posts. At this point I see files in the `_cache` directory starting to appear and also see entries in the cache dashboard over at `/wp-admin/admin.php?page=ajax-load-more-cache`.

But, the response times are with and without the cache enabled 300-500ms. I was hoping for something more like 12ms. I am testing these timings while being logged out.

How can I debug this? My shortcode looks like this:

`<?php echo do_shortcode('[ajax_load_more cache="true" cache_id="1666392211" post_type="post" pause="true" pause_override="true"  category__not_in="8" offset="6" category__not_in="4763,8" posts_per_page="10" scroll_distance="50" max_pages="5" button_label=""]'); ?>`

Running the latest versions of Wordpress, Ajax Load More and the add-on.

**Comment by dcooney** [comment]
@skftn You can test if the cache is working by checking the HTTP request.. If it's response is an HTML file then the cache is working.

Is it possible to share a link?

**Comment by skftn** [comment]
Sure, I sent you an email for the link.

As for the server responses, they seem to return json `{"html": "......"`}`. Response header `Content-Type:application/json`. Response times are 300-500ms, a little too much for local disk access.

**Comment by dcooney** [comment]
Thanks. Closing as this will be solved over email.
