### ISSUE TITLE
Checking user roles and capabilities

### ISSUE THREAD

**Issue by MrCarlLister** [dcooney/wordpress-ajax-load-more#132]
What checks does ALM do before loading in new content? I have a plugin called User Access Manager installed which managers user roles and capabilities within groups (so if user 1 and user 2 are in the same group they can edit each others posts). There's also the option to only allow those in the same group to view each others posts but I don't have this set.

However, ALM doesn't seem to be working now and it's a conflict with this other plugin. This is why I am wondering if there are any checks on the users role / capabilities before displaying posts?

I couldn't find anything specifically but I might be missing it.

Thanks

**Comment by dcooney** [comment]
@MrCarlLister ALM doesn't check user roles before displaying posts. If you need to only display posts for certain users then you could use the [alm_query_args](https://connekthq.com/plugins/ajax-load-more/docs/filter-hooks/#alm_query_args) filter to run a custom query.
