### ISSUE TITLE
Trellis/Composer management errors

### ISSUE THREAD

**Issue by adaamcollins** [dcooney/wordpress-ajax-load-more#133]
First of all, this is a fantastic plugin and has been used on many of the sites I have worked on.

However, I have run into an issue when using this plugin and extensions in a possibly non-standard way, and just wondered if you had an insight into this.

I've recently started managing Wordpress dependencies using Composer, using the Trellis LEMP Stack (https://roots.io/trellis/). Trellis autoloads plugins which are installed and updated using Composer.

It gives us the option to specify "must-use" plugins which are installed into a separate folder (i.e. /mu-plugins/). When we load Ajax Load More (plus any extensions) as a must-use plugin using Composer, the plugin doesn't seem to register that the extensions are installed.

My guess is that the main plugin is looking for extensions in a specific folder/specific location (i.e. the regular '/plugins' directory in a normal Wordpress installation.

Could you shed some light on this?

**Comment by adaamcollins** [comment]
Just a quick update! I actually found the issue behind this. ALM did in fact know that the extension was installed but it wasn't showing under the 'shortcode builder' page in wp-admin because of this function:

`alm_has_addon_shortcodes()`

This only seems to check for add-ons being installed. As soon as I installed any add-on, the ACF extension options showed in the shortcode builder.

It seems that the above function should search for extensions being installed too, otherwise it's hiding the shortcode options for extensions unless you have an add-on installed too?

**Comment by dcooney** [comment]
@adaamcollins Thanks for the heads up and following up on your initial post. I'll check this out and make sure this is updated for next release if I can reproduce the issue.

BTW - what version of ALM are you using?

**Comment by adaamcollins** [comment]
@dcooney No worries, and version 3.1.2 (latest I believe) of ALM.

**Comment by dcooney** [comment]
@adaamcollins I was able to re-create this issue and have fixed it for next release.
