### ISSUE TITLE
Filters not working in combination with WP Super Cache

### ISSUE THREAD

**Issue by jorenvh** [dcooney/wordpress-ajax-load-more#134]
I'm using your plugin in combination with WP Super Cache. Making use the awesome filter function etc. But recently we are having more and more troubles using both of them together. Once a page got cached our content is not loading anymore and we do get the following responses:

XHR request: 200 ok with response: Error, could not verify WP nonce.

Console: 

```
SyntaxError: Unexpected token E in JSON at position 1
    at JSON.parse (<anonymous>)
    at m.parseJSON (jquery.js:4)
    at Pc (jquery.js:4)
    at x (jquery.js:4)
    at XMLHttpRequest.b (jquery.js:4)
```
in ajax-load-more.min.js?ver=3.1.0:1 

**WP version:**  4.7.5 
**Plugin version:** 3.1.0 (I need to update I know & thats planned in the coming month)
**WP super cache version:** 1.4.9

I'm not sure if the issue is caused by ajax load more or by wp super cache so I report this issue at wp super cache as well.

Besides that I think if I would disable the ajax security (wp nonce) it would work but I prefer not to do that for security reasons of course 😉 

ps. Great plugin!

**Comment by dcooney** [comment]
@jorenvh Try turning off Nonce verification under the Ajax Load More settings screen.
Let me know how that works.

**Comment by jorenvh** [comment]
@dcooney turning it off fixes the issue on my machine. Have to verify this by the person who raised the incident in my company.

> EDIT
> 
> Besides that I think if I would disable the ajax security (wp nonce) it would work but I prefer not to do that for security reasons of course 😉
> TBH, this setting is really not required since ALM uses a GET request.

If it's safe to use it that would be the solution. Are there any risks that you know?

**Comment by dcooney** [comment]
No risks I am aware of. That setting is really just legacy... 
At the time when I built the plugin, I was unsure of best practices for admin-ajax usage.

**Comment by jorenvh** [comment]
Ok great, thanks for the very quick support! Have a nice week!
