### ISSUE TITLE
Shortcode Builder examples not working

### ISSUE THREAD

**Issue by oz87** [dcooney/wordpress-ajax-load-more#137]
The **Progress Bar** example works, but **category**, **date**, **author** and **post parameters** examples point to the project url instead of connekthq.com.

**Comment by dcooney** [comment]
@oz87 Not sure what you mean... Can you explain some more.

**Comment by oz87** [comment]
On the Shortcode Builder page, the **view example** links under Category, Date, Author and Post parameters ([screenshot](https://cl.ly/1G0W0L1E132X)). The example for the progress bar directs me to https://connekthq.com/plugins/ajax-load-more/examples/progress-bar/, while the other examples simply add **admin.php?page=ajax-load-more-examples#example-category** to the address bar. [Example of what I mean](https://ozanerel.com/shortcode-examples-not-working/shortcode-builder-examples.mp4)

**Comment by dcooney** [comment]
Oh yes, thanks! I recently changed the URL to the examples so this is broken. Will get this fixed. Cheers.
