### ISSUE TITLE
Error $.fn.almFilter is not a function while trying to use filter

### ISSUE THREAD

**Issue by fleurglansbeek** [dcooney/wordpress-ajax-load-more#138]
Hello,

I need some help regarding the filter option for the Ajax Load More plugin. I used this option to change between category posts, on this [test-domain](http://kelly.fleurglansbeek.nl) it is working. Since I launched this website to my clients domain it stopped working ([example here](http://kellymaakt.nl))..

The following error appears in my browser inspector console tab:

TypeError: $.fn.almFilter is not a function. (In '$.fn.almFilter(transition, speed, data)', '$.fn.almFilter' is undefined)

What am I doing wrong?

Thank you in advance!

**Comment by dcooney** [comment]
Try the solution in the following FAQ question.
https://connekthq.com/plugins/ajax-load-more/docs/faqs/#16

**Comment by fleurglansbeek** [comment]
Thanks for your quick response.

Tried that, but it is still not working.. Here is my code:

jQuery(document).ready(function ($) {
   
   var alm_is_animating = false;// Animating flag
   $('.alm-filter-nav li').eq(0).addClass('active');// Set initial active state
   
   // Btn Click Event
   $('.alm-filter-nav li a').on('click', function(e){    
      e.preventDefault();  
      var el = $(this); // Our selected element     
      
      if(!el.hasClass('active') && !alm_is_animating){ // Check for active and !alm_is_animating  
         alm_is_animating = true;   
         el.parent().addClass('active').siblings('li').removeClass('active'); // Add active state
         
         var data = el.data(), // Get data values from selected menu item
             transition = 'fade', // 'slide' | 'fade' | null
             speed = '100'; //in milliseconds
             
         $.fn.almFilter(transition, speed, data); // Run the filter     
      }      
   });
   
   $.fn.almFilterComplete = function(){      
      alm_is_animating = false; // clear animating flag
   };
});

**Comment by dcooney** [comment]
Not sure... Not seeing the chance on your ref URL

**Comment by fleurglansbeek** [comment]
[Here's the url](http://kellymaakt.nl) If you click on design, video or all it will show the error in the browser inspector console tab.

**Comment by dcooney** [comment]
might be because it's loaded before ajax load more js?
Maybe try moving the function to a custom JS file and loading it after ajax load more.

**Comment by fleurglansbeek** [comment]
I tried and it worked :)!

Thank you for your help, appreciate it!
