### ISSUE TITLE
Doesn't process shortcodes used in Posts

### ISSUE THREAD

**Issue by avidsapp** [dcooney/wordpress-ajax-load-more#139]
Shortcodes used in the Post content are displayed in `<p>` tags and not processed.

`<?php do_shortcode(the_content()); ?>` doesn't work

Neither does:
```
<?php $content = get_the_content();
	echo do_shortcode($content); ?>
```

Is there a way to apply the `do_shortcode()` to the output filter like so:
```
add_filter( 'widget_text', 'shortcode_unautop');
add_filter( 'widget_text', 'do_shortcode', 11);
```

**Comment by dcooney** [comment]
@avidsapp Are you talking about shortcodes being rendered with a Repeater Template? Soemtimes other plugin shorcodes do have issues.
This FAQ question may help.
https://connekthq.com/plugins/ajax-load-more/add-ons/previous-post/#3

**Comment by avidsapp** [comment]
Thank you! I looked through the docs, but didn't see this. Fixed.
