### ISSUE TITLE
Improvements to get CAT, TAG, SEARCH and DATE

### ISSUE THREAD

**Issue by mcunha98** [dcooney/wordpress-ajax-load-more#14]
Hi

Here my custom version of the template to get values from request.
Notice that I put the new tag <b>data-date </b> to get the query values from calendar or month combo archive.
 
	<section id="ajax-load-more">
		<div id="post-area">
			<div class="listing" data-path="<?php echo get_template_directory_uri(); ?>/ajax-load-more" data-post-type="post" data-category="<?php if (isset($_REQUEST["cat"])) echo($_REQUEST["cat"]); ?>" data-date="<?php if (isset($_REQUEST["m"])) echo($_REQUEST["m"]); ?>" data-taxonomy="<?php if (isset($_REQUEST["s"])) echo($_REQUEST["s"]); ?>" data-tag="<?php if (isset($_REQUEST["tag"])) echo($_REQUEST["tag"]); ?>" data-display-posts="<?php echo get_option('posts_per_page'); ?>" data-scroll="false" data-button-text="<?php _e('Next page','default'); ?>"></div>
		</div>
	</section>	

At now don't work, but I near to implement it.
I'm working on it:

<code>
$args = array(
	'post_type' 			=> $postType,
	'category_name' 		=> $category,	
	'author'				=> $author_id,
	'posts_per_page' 		=> $numPosts,
	'paged'          		=> $page,
	//'year'					=> $year,
	//'monthnum'				=> $month,
	'orderby'   			=> 'date',
	'order'     			=> 'DESC',
	'post_status' 			=> 'publish',
	'ignore_sticky_posts' 	=> true,
);
</code>

**Comment by dcooney** [comment]
Date queries are available in 2.4.0
https://wordpress.org/plugins/ajax-load-more/
