### ISSUE TITLE
Uncaught TypeError: a.imagesLoaded is not a function on mobile

### ISSUE THREAD

**Issue by kirsty-gasston** [dcooney/wordpress-ajax-load-more#141]
Similar to issue #135, we're getting the following issue:

```
Uncaught TypeError: a.imagesLoaded is not a function
    at t (ajax-load-more.min.js?ver=3.3.1:1)
    at Object.o.AjaxLoadMore.success (ajax-load-more.min.js?ver=3.3.1:1)
    at Object.success (ajax-load-more.min.js?ver=3.3.1:1)
    at i (jquery.js?ver=1.12.4:1)
    at Object.fireWith [as resolveWith] (jquery.js?ver=1.12.4:1)
    at y (jquery.js?ver=1.12.4:1)
    at XMLHttpRequest.c (jquery.js?ver=1.12.4:1)
```

However, this only happens on mobile devices, on desktop there are no issues. We have tested on Android and iOS devices and using both Chrome and Firefox.

The shortcode we are using is:

```
<?php echo do_shortcode('[ajax_load_more id="1971232832" container_type="div" users="false" users_role="undefined" users_include="undefined" users_exclude="undefined" users_per_page="undefined" users_order="undefined" users_orderby="undefined" post_type="post" transition="masonry" masonry_selector=".grid-item" masonry_animation="slide-up"]'); ?>
```

We are on WordPress 4.9 and version 3.3.1 of Ajax Load More and are using the built-in Masonry.

**Comment by dcooney** [comment]
@kirsty-gasston Not really sure what would cause this. When `masonry="true"` I enqueue ImagesLoaded and Masonry from WP Core.

```
if($transition === 'masonry'){
      wp_enqueue_script( 'imagesloaded' ); // Enqueue before core ALM
      wp_enqueue_script( 'masonry' ); // Enqueue before core ALM
}
```

Could there be something in your theme removing these libraries on mobile?

**Comment by kirsty-gasston** [comment]
@dcooney Just been doing more testing and now I can seemingly get this to work on both desktop and mobile, but only when logged into the WordPress admin - if I am logged out it does not work at either desktop or mobile with the same error:

```
Uncaught TypeError: a.imagesLoaded is not a function
    at t (ajax-load-more.min.js?ver=3.3.1:1)
    at Object.o.AjaxLoadMore.success (ajax-load-more.min.js?ver=3.3.1:1)
    at Object.success (ajax-load-more.min.js?ver=3.3.1:1)
    at i (jquery.js?ver=1.12.4:2)
    at Object.fireWith [as resolveWith] (jquery.js?ver=1.12.4:2)
    at y (jquery.js?ver=1.12.4:4)
    at XMLHttpRequest.c (jquery.js?ver=1.12.4:4)
```

**Comment by dcooney** [comment]
Sounds like a cache issue or something in your theme is blocking the scripts from loading.

**Comment by kirsty-gasston** [comment]
Caching is all switched off on this site and we've checked all the theme files and can see nothing that would block the scripts from loading

**Comment by dcooney** [comment]
Ok. Please share a link so I can have a look then. Thanks.

**Comment by dcooney** [comment]
@kirsty-gasston Did you ever solve this issue? Another user has the same thing happening... obviously a really small use case since it's been over a year, but just curious.
