### ISSUE TITLE
Uncaught TypeError: a.imagesLoaded is not a function (desktop)

### ISSUE THREAD

**Issue by endlist** [dcooney/wordpress-ajax-load-more#142]
I saw there were two similar issues #135 and #141, but I'm not really sure I understand how it was fixed for the former, and it's happening on desktop for me, not just mobile.

Using this shortcode in my template:

```php
echo do_shortcode('[ajax_load_more post_type="jetpack-portfolio" transition="masonry" masonry_selector=".grid-item" masonry_animation="slide-up"]');
```

I'm only using the scripts as provided by the plugin, and they do appear to load
<img width="672" alt="screen shot 2018-02-22 at 1 54 58 pm" src="https://user-images.githubusercontent.com/453902/36563677-26ceb274-17d8-11e8-9216-8c90ae001390.png">

The shortcode displays posts if I take out the masonry arguments, but once I add them in it gives me the error

```
Uncaught TypeError: a.imagesLoaded is not a function
    at t (ajax-load-more.min.js?ver=3.4.1:1)
    at Object.o.AjaxLoadMore.success (ajax-load-more.min.js?ver=3.4.1:1)
    at Object.success (ajax-load-more.min.js?ver=3.4.1:1)
    at i (jquery.js?ver=1.12.4:2)
    at Object.fireWith [as resolveWith] (jquery.js?ver=1.12.4:2)
    at y (jquery.js?ver=1.12.4:4)
    at XMLHttpRequest.c (jquery.js?ver=1.12.4:4)
```

And the posts are never loaded.

**Comment by dcooney** [comment]
@endlist I'm not really sure why this happens as I've never been able to replicate the issue.
If at all possible, can you throw the site up on a dev server so I can see the issue?

**Comment by dcooney** [comment]
Another user had this issue and turns out the problem was jQuery being loaded after imagesLoaded and Masonry.

**Comment by northbeachmedia** [comment]
Hi, I'm running into the same issue and jQuery is being loaded after the imagesLoaded section. Any suggestions on how to fix this?

**Comment by dcooney** [comment]
@northbeachmedia This seems to appear when users have multiple versions of jQuery being loaded. Confirm you don't please.
