### ISSUE TITLE
Feature request: Ability to add classes to container, button

### ISSUE THREAD

**Issue by mrjustin** [dcooney/wordpress-ajax-load-more#143]
Love the ability to add classes to the `alm-listing` container, but it would be great to also be able to add classes to the main container `ajax-load-more-wrap`, the button container `alm-btn-wrap`, and the button itself `alm-load-more-btn`

I'm developing most sites these days with functional/atomic CSS and would love the ability to add "mb3 w-100 etc." classes to these elements rather styling these in a CSS file.

Thanks!

**Comment by dcooney** [comment]
@mrjustin You can add classes to the ALM button on the ALM settings screen. 
I'll consider adding some settings or filters for these other elements.

**Comment by mrjustin** [comment]
@dcooney Ah, right! Forgot about the Button Classes section in global settings. That helps. Would still love the ability to override within the shortcode + those others. Thanks so much!
