### ISSUE TITLE
FEATURE REQUEST: Fetch terms (instead of posts)

### ISSUE THREAD

**Issue by tnightingaleza** [dcooney/wordpress-ajax-load-more#144]
FEATURE REQUEST: Hi there! Would love to be able to use ALM to display terms, instead of just posts. E.g, allowing my users to scroll through all the terms found in a custom taxonomy. Currently using get_terms to output all available terms - sucks not to have beautiful Ajax Load More on this page.

**Comment by dcooney** [comment]
https://connekthq.com/plugins/ajax-load-more/extensions/terms/
