### ISSUE TITLE
Urgent: "posts_per_page" not working with preloaded and seo plugin combination.

### ISSUE THREAD

**Issue by Stuckya** [dcooney/wordpress-ajax-load-more#148]
### Here is my shortcode: 

`[ajax_load_more paging="true" paging_controls="true" paging_show_at_most="7" preloaded="true" seo="true" theme_repeater="blog_block.php" post_type="post" posts_per_page="3" pause="true" scroll="false"]`

### I have the following add-ons installed:

Ajax Load More v3.5.1
- Paging v1.3.4
- Preloaded v1.3.0
- Search Engine Optimization v1.7.2
- Theme Repeaters v1.1

### Desired Functionality:

A simple blog index with paginated posts, with 3 posts displayed per page. Those 3 pages should be preloaded on page load. I want to show 7 pages at most because there are some 700 posts total. I don't want any scrolling functionality.

### The problem:

It appears not all attributes are being passed from shortcode to the data attributes in the markup.
So I see a total of 10 posts per page no matter what I do with the shortcode.

<img width="1561" alt="screen shot 2018-06-30 at 3 08 01 pm" src="https://user-images.githubusercontent.com/35773719/42128355-76c0e2e4-7c77-11e8-8066-bbfa88e29f98.png">

### Server environment:

LAMP stack running on Ubuntu 16.04
Using PHP 7.0.28

### What I have done to test:

Ensured it isn't a browser specific issue.
I've tested in Chrome, Firefox Developer Edition, and Safari with no success.

**Comment by dcooney** [comment]
Issue is covered in the docs.
https://connekthq.com/plugins/ajax-load-more/add-ons/search-engine-optimization/#postsperpage
