### ISSUE TITLE
Button Stuck In Masonry Layout

### ISSUE THREAD

**Issue by Sleigh** [dcooney/wordpress-ajax-load-more#154]
This might be obvious, but I am exhausted at this point - so thank you for reading.  I am using your wonderful pluggin to load new posts in a masory-like layout (they're all the same size though for now).  For example, on desktop, the button is centered, but then after it is clicked, the button reloads in the right column. Is there a way to make the button always centered for the whole page, while not borking the masonry-ish layout?  Thanks!

**Comment by dcooney** [comment]
Hi @Sleigh, I'm not sure i'm following the issue 100%... Can you share a link to the issue?

**Comment by Sleigh** [comment]
https://www.ypo.org/ignite/  Thank you!

**Comment by dcooney** [comment]
Thanks... Ok, your issue is you have a `.masonry` div outside of ALM container, and `.masonry` has a grid column layout.

Remove this div and add the following `css_classes="masonry"` parameter to your shortcode.

`[ajax_load_more css_classes="masonry" {the rest of your shortcode} ]`

**Comment by Sleigh** [comment]
THAT WAS IT!  THANK YOU! AH!!

**Comment by dcooney** [comment]
Nice !
