### ISSUE TITLE
Sort and filter by custom field (ACF)

### ISSUE THREAD

**Issue by roun512** [dcooney/wordpress-ajax-load-more#156]
Greetings,

So I've been trying to merge search with filter on one of my projects, now I can filter results by custom fields, and sort by custom field. But I can't do both together for some reason?

For the sort I'm approaching it like this (just example):
`[ajax_load_more order="DESC" meta_key="price" orderby="meta_value_num"]`

For the filtering I'm using this:
`[ajax_load_more meta_key="country:city" meta_value="12:23" meta_compare="LIKE:LIKE" meta_type="CHAR:CHAR"]`

So how can I merge these two together?

**Comment by dcooney** [comment]
@roun512 You'll have to use this filter to accomplish that.
https://connekthq.com/plugins/ajax-load-more/docs/filter-hooks/#alm_query_args

I like the idea of adding a custom parameters for specifically ordering by `meta_key` though. Something like `meta_key_order`. I'll add this to an upcoming release.

**Comment by roun512** [comment]
That works, thank you so much for the help :)
