### ISSUE TITLE
Ajax request string parameters not url encoded

### ISSUE THREAD

**Issue by crobbinsdg** [dcooney/wordpress-ajax-load-more#160]
Specifically I am looking at the `canonical_url` parameter.  Previous to 5.x the `canonical_url` was encoded so that it looked like `https%3A%2F%2Fwww.google.com%2F`.  With 5.x it looks like `https://www.google.com/`.

This came up because I was getting 403 errors when I upgraded to 5.x.  The ajax requests were being blocked due to mod security rules on the server and rewrite rules set by a security plugin.  Specifically those rules look for `https://` in the url string.

I saw 5.x uses a different library for requests.  Perhaps this is causing the request params to not be encoded.

**Comment by dcooney** [comment]
@crobbinsdg Thanks for pointing this out. I was trying to figure out a solution for this. I'll try to encoded them and see what happens.

Yes, I switched for jquery.ajax to Axios for http requests.

**Comment by dcooney** [comment]
Patch for this was added in 5.0.2.
https://wordpress.org/plugins/ajax-load-more/#developers
