### ISSUE TITLE
woocommerce orderby

### ISSUE THREAD

**Issue by funkysoul** [dcooney/wordpress-ajax-load-more#162]
Did anyone successfully managed to use woocommerce's sorting with ajax load more? 
I'm trying to sort by price (asc, desc) and by popularity.  Both queries that are not documented in ALM. Many thanks for any input ;-)

**Comment by dcooney** [comment]
@funkysoul The sort by price you should do this.
`[ajax_load_more meta_key="_price" orderby="meta_value"]`

`_price` is the custom field key for price, Im not sure what popularity is.

**Comment by dcooney** [comment]
@funkysoul Looks like popularity might be total_sales

So: `[ajax_load_more meta_key="total_sales" orderby="meta_value"]`
