### ISSUE TITLE
No posts load

### ISSUE THREAD

**Issue by blorange2** [dcooney/wordpress-ajax-load-more#164]
I have a WordPress installation in which I'm using Sage and Sage Directives. I installed this plugin and followed the instructions in the documentation.

My template file looks like this:

```

<div class="col-12 col-md-6 col-lg-3">
    <div class="story-card d-flex d-md-block flex-row">
        <a href="<?php the_permalink(); ?>" class="story-card__anchor">
            <div class="story-card__image-container d-flex order-1 d-md-block">

                <div class="story-card__image" style="background-image: url(<?php the_post_thumbnail_url(); ?>);"></div>
                <div class="story-card__category">
                    <div class="story-card__category-box-left"></div>
                    <div class="story-card__category-box-right"></div>
                    <div class="story-card__category-box-top"></div>
                    <span class="story-card__category-box-text">{{ $category }}</span>
                </div>
            </div>
            <div class="story-card__content-wrapper d-flex flex-column order-0 d-md-block">
                <small class="story-card__publish-date"><?php the_date();</small>
                <div class="story-card__title"><?php the_title(); ?></div>
            </div>    
        </a>
    </div>
</div>

```

Then I have a page template called `news-listing` in my theme with the following snippet:

```

$args = array(
    'post_type' => 'post',
    'post_status' => 'publish',
    'orderby' => 'publish_date',
    'order' => 'DESC',
    'posts_per_page' => '2',
    'button_label' => 'Load more...',
    'button_loading_label' => 'Loading...',
    'scroll' => 'false'
);	

if(function_exists('alm_render')){
    alm_render($args);
}

```

This renders the load more button but no posts. 

For this plugin to work do I have to manually initialise the WordPress loop first using WP_Query?

Using `Sage Directives you can do the following:

```

@query([
    'post_type' => 'post',
    'post_status' => 'publish',
    'orderby' => 'publish_date',
    'order' => 'DESC',
    'paged' => 1
])

@posts
<!-- post card here -->
@endposts

```

**Comment by dcooney** [comment]
Hi @blorange2 
Unfortunately, I have not had any success with using Sage directives or anything to do with Blade templating in Repeater Templates.

I think the issue is the classes required are not loaded in `admin-ajax.php` requests.

In your case, is the template rendering the HTML, but just not the content?

> For this plugin to work do I have to manually initialise the WordPress loop first using WP_Query?
No, ALM creates the query for you based on shortcode parameters.

**Comment by blorange2** [comment]
Hi @dcooney 

So, in theory that part is very similar in nature as it creates the query? I'll have a few more stabs and report my findings.
