### ISSUE TITLE
IE 11 script error

### ISSUE THREAD

**Issue by amitosdev** [dcooney/wordpress-ajax-load-more#165]
I installed v5.2.0 of the plugin on WordPress v5.3.2. On IE 11 posts are not loaded. I see the following error in the console:
![image](https://user-images.githubusercontent.com/15922250/76767623-93c8e180-67a2-11ea-9dd0-373e8b675241.png)

Thanks!

**Comment by amitosdev** [comment]
Looks like it is something that related to the polyfill module you guys using, can you please update it and recompile?

**Comment by dcooney** [comment]
Yes, it happens when other scripts are using the same polyfill. this is on my list to fix for next release.
