### ISSUE TITLE
Not working with LiteSpeed Cache plugin JS minify option

### ISSUE THREAD

**Issue by dmitry-christie** [dcooney/wordpress-ajax-load-more#167]
Hello,

I've noticed that the 'load more' button is not loading when I enable JS minify setting in LiteSpeed Cache.

Temporary fix: Tuning Settings -> JS Excludes add 'ajax-load-more.min.js'.

Permanent solution: 
adding " wp_script_add_data('ajax-load-more', 'data-no-optimize' , '1'); " to alm_enqueue_scripts().

Thanks,

Hope that helps.

Dmitry

**Comment by dcooney** [comment]
Issue merged.
