### ISSUE TITLE
pace.min.js is corrupting XMLHttpRequest.DONE value

### ISSUE THREAD

**Issue by a2intl** [dcooney/wordpress-ajax-load-more#170]
We had a customer that was using this plugin report a bug that our Consent Manager (Quantcast Choice) was not working. We tracked it down `XMLHttpRequest.DONE` no longer having a value of `4` due to an override done by `extendNative` at 

https://github.com/dcooney/wordpress-ajax-load-more/blob/master/vendor/js/pace/pace.js#L444

The specific bug is on line

https://github.com/dcooney/wordpress-ajax-load-more/blob/master/vendor/js/pace/pace.js#L360 

where `key` is not localized per loop iteration, so all the properties of the "extended-native" version of XMLHttpRequest end up retrieving the last-property-iterated.

I don't see a fix in the latest version of pace-js on github: https://github.com/HubSpot/pace/blob/master/pace.js , but I think you can fix this by replacing lines 359-361 with:

```
              get: (function(keyIn) { return function() {
                return from.prototype[keyIn];
              })(key),
```

**Comment by a2intl** [comment]
It looks like this has been reported as https://github.com/HubSpot/pace/issues/261

**Comment by a2intl** [comment]
I've submitted a fix https://github.com/HubSpot/pace/issues/261 which has been merged upstream, if you want to grab the new pace.js and pace.min.js files.

**Comment by dcooney** [comment]
Thanks @a2intl I've added this update to the next ALM update. `5.4.0`
