### ISSUE TITLE
scroll="false" doesnt work for the first time...

### ISSUE THREAD

**Issue by vijarp** [dcooney/wordpress-ajax-load-more#175]
So if I have 10 rows and I place [ajax-load-more scroll="false"] - it displays 20 rows and then a button..Ideally it should show button after 10 rows itself...It works correctly on mobile but on desktop - there is a bug..

**Comment by dcooney** [comment]
@vijarp Share a link to the issue please. Likely a config or implementation issue.

**Comment by vijarp** [comment]
@dcooney  https://30a.com/news - It loads 20 items

**Comment by dcooney** [comment]
Looks like you're loading 10 posts before Ajax Load More, then 10 via ALM. Set `pause="true"` to not load posts on page load.
