### ISSUE TITLE
Get current page slug raises an issue if alm instance is in the author page's context

### ISSUE THREAD

**Issue by Abdelmonem-BEN-NACEUR** [dcooney/wordpress-ajax-load-more#176]
Since the `global $post` variable is empty in the author page, we got this warnings in the author page : 

```
 Notice: Trying to get property 'post_name' of non-object in \wp-content\plugins\ajax-load-more\core\functions.php on line 456
 Notice: Trying to get property 'ID' of non-object in \wp-content\plugins\ajax-load-more\core\functions.php on line 533
```

I fixed it in my theme with a small workaround, but it would be better if you consider it in your coming updates!

Thank you in advance!

**Comment by dcooney** [comment]
@Abdelmonem-BEN-NACEUR What is your work around, please?

**Comment by Abdelmonem-BEN-NACEUR** [comment]
Since in my case, I don't need to work on the `global $post` variable, I declared it as an empty object on the fly and populate it, so that ALM will have what it expected, this is very specific to my use case and this should be handled in the plugin itself. 

```
global $post;
$post            = new stdClass();
$post->ID        = get_the_author_meta( 'ID' );
$post->post_name = get_the_author_meta( 'display_name' );
```

**Comment by dcooney** [comment]
I'm having a look here and line 456 and 533 of `core/functions.php` should only be run on non-archove templates.
![image](https://user-images.githubusercontent.com/428624/109435304-da314380-79e7-11eb-9b56-6c058ab0c146.png)

If this is an author archive, it should not be hitting this conditional.

**Comment by Abdelmonem-BEN-NACEUR** [comment]
In fact `is_archive()` returns `false` inside this template file : `alm_templates/default.php` in the theme root. That's why it hits this conditional.
![image](https://user-images.githubusercontent.com/30234640/109491304-af97c700-7a89-11eb-83cd-57adb20ad669.png)

**Comment by dcooney** [comment]
No, it's not.
`core/functions.php` is not called from a Repeater Template.
