### ISSUE TITLE
Ajax load more : Next page add-on admin settings

### ISSUE THREAD

**Issue by krishnaphpdev** [dcooney/wordpress-ajax-load-more#177]
Hi Team,

Don't we have save settings button in ajax-load-more: next page add-on, I didn't and even its not saving auto also, below is screen.

![image](https://user-images.githubusercontent.com/84961860/120796433-71aeb100-c558-11eb-9781-5b13a5e55e2b.png)

Please suggest may be I am wrong or confused.

**Comment by dcooney** [comment]
@krishnaphpdev This is not settings, it's the Shortcode Builder. There is nothing to save here. Make a change and it appears on the right in the **Shortcode Output** section.

**Comment by krishnaphpdev** [comment]
I have tried below short code  but not working the next page loading as per demos in plugin page 

[ajax_load_more container_type="ul" nextpage="true" nextpage_post_id="'.get_the_ID().'" nextpage_title_template="{post-title}" nextpage_scroll="false:30" post_type="post, page, attachment, any" pause="true" images_loaded="true" placeholder="true" button_label="Next page" no_results_text="no result found"]

Have tried different method and code inserted as per docs provided.

**Comment by dcooney** [comment]
@krishnaphpdev Please open a support ticket and share a link so I can see if there is a JS error
https://connekthq.com/support/?product=Ajax%20Load%20More
