### ISSUE TITLE
html: false on first page

### ISSUE THREAD

**Issue by caspahouzer** [dcooney/wordpress-ajax-load-more#179]
With `/wp-admin/admin-ajax.php?id=&post_id=0&slug=home&posts_per_page=9&page=1&offset=1&post_type=post&repeater=default&seo_start_page=1&preloaded=false&preloaded_amount=0&order=DESC&orderby=date&action=alm_get_posts&query_type=standard`
I got this result
```
{
    "html": false,
    "meta": {
        "postcount": 9,
        "totalposts": 622,
        "debug": false
    }
}
```
next scroll/button push with this url `/wp-admin/admin-ajax.php?id=&post_id=0&slug=home&posts_per_page=9&page=2&offset=1&post_type=post&repeater=default&seo_start_page=1&preloaded=false&preloaded_amount=0&order=DESC&orderby=date&action=alm_get_posts&query_type=standard` works.

How do I get the first page request working???

Thanks in advance for your help

**Comment by dcooney** [comment]
@caspahouzer I haven't seen this `false` response before.
Is your [Repeater Template](https://connekthq.com/plugins/ajax-load-more/docs/repeater-templates/) empty by chance?

**Comment by caspahouzer** [comment]
I had to encode the result by utf-8. damn german language 😄
