### ISSUE TITLE
pre_get_posts - is_admin() returning true when loaded from public page

### ISSUE THREAD

**Issue by 14nd90** [dcooney/wordpress-ajax-load-more#180]
Thanks for the great plugin, but this issue sent me round in circles for a while! 

I'm loading ALM through do_shortcode() in my taxonomy template:

```
$queried_object = get_queried_object();
$tax = $queried_object->taxonomy;
$tax_name = $queried_object->name;
$tax_term = $queried_object->slug;
echo do_shortcode('[ajax_load_more post_type="post" posts_per_page="9" taxonomy="'. $tax .'" taxonomy_terms="'. $tax_term .'" taxonomy_operator="IN" transition="masonry" masonry_animation="zoom-out" masonry_selector=".entry" css_classes="posts posts-list" container_type="div"]');
```

Surely it shouldn't be the case that the is_admin() flag is true in the pre_get_posts filter when viewing my public taxonomy page?

**Comment by 14nd90** [comment]
OK yes that makes sense, I am reading all requests to admin_ajax even with _nopriv are treated as from being within the admin area. Thanks for the pointer

**Comment by diversityX** [comment]
Issues "round in circles awhile". Why didn't this offend you @dcooney?  Just stopping by and letting everyone know how abusive you are to customers of your plugins. I would bet with your temper, its difficult to find other developers to work with.
