### ISSUE TITLE
internal penetration test flagged for xs

### ISSUE THREAD

**Issue by thihaz** [dcooney/wordpress-ajax-load-more#183]
In this file, \ajax-load-more\core\classes\class-alm-shortcode.php

line 1237 was flagged as Cross-Site Scripting (Reflected) by internal penetration test. (js script was passed through and printed out)

Following line 1234 has $_SERVER['QUERY_STRING'] which should be sanitized before assigned it to a variable. 
// Get current permalink - (including querystring).
$single_post_permanlink = ( $_SERVER['QUERY_STRING'] ) ? get_permalink( $single_post_id ) . '?' . $_SERVER['QUERY_STRING'] : get_permalink( $single_post_id );

Please let me know if this is not a concern. Thank you.

**Comment by dcooney** [comment]
This is fixed for the next ALM release. `5.5.3`
