### ISSUE TITLE
Feature Request: Optional preloaded wrapper

### ISSUE THREAD

**Issue by amdd-tim** [dcooney/wordpress-ajax-load-more#191]
Currently, if I choose to preload a set amount of posts, those posts are wrapped in an .alm-preloaded div. As the documentation notes, this is nice if you want to specifically style those preloaded posts. However, if, as in my case, you're already removing the .alm-reveal wrapper, this creates a problem because the preloaded post nodes are not siblings of the posts loaded later via ajax. E.g., One might want all the posts, preloaded and ajax loaded, to be part of the same CSS grid.

Is it possible to either add another shortcode parameter to turn this wrapper off or at least not display it if `transition_container` is false? As it stands, I have to have that container removed, so I've resorted to editing ajax-load-more/core/classes/includes/preloaded.php directly.

**Comment by dcooney** [comment]
@amdd-tim This is finally fixed in the next version of ALM. Should be released tomorrow.
Better late than never? :)
