### ISSUE TITLE
Losing repeaters when update plugin

### ISSUE THREAD

**Issue by contteudo** [dcooney/wordpress-ajax-load-more#36]
Hi. When I need to update the plugin for the last version, the default and my custom repeaters templates are losing. Please, correct this. :)

**Comment by dviramontes** [comment]
Hi @dcooney - i just updated the plugin to version `3.5.1` and it broke existing functionality. I don't know what the previous version used to be so i'm not able to downgrade and compare. Has there been at any point breaking changes in any of the plugin releases ?

**Comment by dcooney** [comment]
@dviramontes  3.5 moved the Repeater Template from the plugin folder to `alm_templates` inside the WP Uploads directory.
