### ISSUE TITLE
Load more comments on demand

### ISSUE THREAD

**Issue by Slamik** [dcooney/wordpress-ajax-load-more#40]
Due to request on wordpress.org.
https://wordpress.org/support/topic/feature-request-loading-more-comments-on-demand

Thank you in advance!

**Comment by dcooney** [comment]
Comments supported by add-on.
https://connekthq.com/plugins/ajax-load-more/add-ons/comments/

**Comment by abelpedro** [comment]
This site is amazing and always has a taste of reading like the posts here. Congratulations.
https://www.estudaringlesonline.com.br/
