### ISSUE TITLE
Load more order by random 

### ISSUE THREAD

**Issue by melfred0426** [dcooney/wordpress-ajax-load-more#51]
Hi sir , This plugin so very helpful . But there's a problem with regard to the order by rand . Once I clicked the Load more some of the items duplicate . Is there a change that we can exclude the first items load more then load another items

We will appreciate you quick response.
Thanks

**Comment by jan1980** [comment]
Hi Darren, thanks for this amazing plugin.
One question, could you recommend us some temporary fix? Is there any part that we may tweak on the code?

Best regards,

**Comment by dcooney** [comment]
Hey, 
I've been unsuccessful solving this one. I hope to circle back to this in the near future.

**Comment by zocoloco** [comment]
Hi Darren... have you tried post__not_in  for every query after the first? Easier that storing a list of previously loaded.

**Comment by dcooney** [comment]
Yea I have, the issue I ran into is storing the array of previously loaded posts. It sounds simple, but the ajax calls and the current set up of the plugin make it challenging.

**Comment by wintermute2000** [comment]
Hi, has there been any luck in solving this issue? Thanks in advance.

**Comment by Danny-weebo** [comment]
I didn't see anything relevant in the documentation but if someone still looking for random sort you can just add `orderby="rand` to the ajax_load_more shortcode and it works great.

**Comment by dcooney** [comment]
@Danny-weebo Yes, but it will display duplicates.

**Comment by Danny-weebo** [comment]
hey, is there any solution for it by now ?

thanks :)
