### ISSUE TITLE
Not working ajax load more

### ISSUE THREAD

**Issue by kenchan0130** [dcooney/wordpress-ajax-load-more#56]
When send a request for admin-ajax.php, occurred "Error, could not verify WP nonce".
It seems that `wp_verify_nonce($nonce, 'ajax_load_more_nonce')` is invalid.

My environment: 
```
PHP: 5.5.20 (cli) (built: Dec 17 2014 15:09:12)
httpd: Apache/2.2.15 (Unix)
Wordpress: 4.1
```

**Comment by kenchan0130** [comment]
FYI, when i remove or comment out

```php
if (! wp_verify_nonce( $nonce, 'ajax_load_more_nonce' ))
  die('Error, could not verify WP nonce.');
```
 
I can get response.

**Comment by dcooney** [comment]
Yea the nonce is there for security purposes. You likely don't want to comment that out.
Which browser is this happening in?

**Comment by kenchan0130** [comment]
Yeah, I've understood security purposes.
I used Google Chrome latest ver.

**Comment by dcooney** [comment]
Hi, Nonce verification has been removed in 2.6.3 and is now a setting you can turn [on][off]

**Comment by kenchan0130** [comment]
Thank you for your kind correspondence!
