### ISSUE TITLE
How to fix: Disables SEO if $preload?

### ISSUE THREAD

**Issue by mihdan** [dcooney/wordpress-ajax-load-more#62]
// Disables SEO if $preload
// To be removed in future versions
if($seo === 'true' && $preloaded === 'true')
    $seo = 'false';

**Comment by dcooney** [comment]
Hi,
Currently SEO and Preload are not able to work together.
Is that what you looking to fix?

**Comment by mihdan** [comment]
Yes (

**Comment by dcooney** [comment]
Yea sorry, an update for this should be coming fairly soon.

**Comment by mihdan** [comment]
ok

**Comment by mihdan** [comment]
Thx.
