### ISSUE TITLE
IDs option for the shortcode

### ISSUE THREAD

**Issue by eatwholegrain** [dcooney/wordpress-ajax-load-more#63]
Hi dcooney,

Will there be a possibility to show only the posts with the selected IDs in the Load More loop?

E.g. I want to show only posts with post IDs (47, 58, 59, 111, 123, 135, 167, 198, 234, 255) and want to show them by loading only 4 at a time.

Why is it important?
- e.g. I have a site where users can mark posts as favorites. Now I have to load ALL posts from the db and then Exclude all posts that are not favourites >> which makes the whole process more difficult.
- if I had this option, I could make any custom query, even if it's not supported by your plugin at the moment (then switch to the standard solution with the plugin parameters when it becomes supported in a future version)

Actually this what I'm exactly talking about (from WP_Query documentation):

**Multiple Posts/Pages Handling**
Display only the specific posts:
$query = new WP_Query( array( 'post_type' => 'page', 'post__in' => array( 2, 5, 12, 14, 20 ) ) );

It will also need an ignore_sticky_posts option, because these are automatically added...

Thanks in advance if this can be implemented.

Ervin

**Comment by dcooney** [comment]
Hi Ervin,
this is not possible currently... It's possible I could add this in though. Let me think about it.

**Comment by eatwholegrain** [comment]
I can see it in the newest version, with the post_in attribute. Thanks for implementing, it really helps!

**Comment by dcooney** [comment]
No problem!
