### ISSUE TITLE
Auto load-more is not triggered

### ISSUE THREAD

**Issue by GabrielCousin** [dcooney/wordpress-ajax-load-more#64]
It seems that the condition is never true in my case. I need to add a margin-bottom on the button wrapper.
Maybe you need to decrease 150 on this (line 213):
`Math.round(content_offset.top - (alm.window.height() - 150))`

**Comment by dcooney** [comment]
In the next version. 2.6.0, '150' is now a variable you can set within the shorcode builder. 
Expect that release within 1.5 weeks.

**Comment by GabrielCousin** [comment]
Awesome! Thanks for your answer :)

**Comment by dcooney** [comment]
np!
