### ISSUE TITLE
Exclude shortcode argument not work with preloaded plugin

### ISSUE THREAD

**Issue by mihdan** [dcooney/wordpress-ajax-load-more#65]
because:

exclude -> post__not_in

http://codex.wordpress.org/Class_Reference/WP_Query#Post_.26_Page_Parameters

fixed:

```PHP
add_filter( 'alm_preload_args', function( $args ) {
	if ( ! empty( $args['exclude'] ) ) {
		$args['post__not_in'] = explode( ',', $args['exclude'] );
		unset( $args['exclude'] );
	}
	return $args;
});
```

**Comment by dcooney** [comment]
Just tested and `Exclude` is working for me in both Preloaded and the core Ajax Load More.

Are you having a specific issue?
