### ISSUE TITLE
Can't load last version of repeater template

### ISSUE THREAD

**Issue by GabrielCousin** [dcooney/wordpress-ajax-load-more#68]
Thanks a lot for your last update.
I am encountering a new issue: when trying to update the default repeater template, template is normally saved, but nothing has changed where I call the shortcode.

```[ajax_load_more post_type="post" repeater="default" offset="2" posts_per_page="3" transition="slide" pause="false" scroll="true" button_label="Load more…"]```

**Comment by dcooney** [comment]
No errors in your console? What if you refresh the repeater template in the admin, has it changed?

**Comment by GabrielCousin** [comment]
Console is empty. The template is updated as expected in the backoffice.

**Comment by dcooney** [comment]
That's strange, sounds like its cached or something. Has the file changed on the server?
/ajax-load-more/core/repeater/default.php

**Comment by GabrielCousin** [comment]
The file is updated as well…
I don't know if it could help, but I updated the plugin this morning and then tried to change the repeater.

**Comment by dcooney** [comment]
not really sure -  I'm out of ideas, unless u want to give me access to your site.

**Comment by GabrielCousin** [comment]
I'm deeply sorry, it is my own fault. I just forgot I used a query in my template and call the repeater with an offset of 2 posts. Please excuse me.
Thanks again for your awesome plugin.
