### ISSUE TITLE
Not compatible with Pantheon

### ISSUE THREAD

**Issue by nik-cole** [dcooney/wordpress-ajax-load-more#72]
I have seen a few noted issues on WP Engine, which seems to happen with Pantheon as well.

Once I updated and pushed to live, because file permissions are restricted it breaks the dashboard and functionality stops working.  Just curious, have you found work around for this or plan to address this?

Great job on this plugin by the way, we use on a number of our sites and would love to continue to however we can't update it.

Thanks for your time!

**Comment by dcooney** [comment]
Hi,
Sorry for the trouble! Yes this updating issue is next on my agenda as soon as I get my next plugin out the door, which is hopefully Thursday.

First up will be stopping the plugin from breaking the WP dashboard, next up will be setting up a Pantheon test account to troubleshoot.

Do you happen to know if it's possible to set up a free account with Pantheon?

**Comment by nik-cole** [comment]
Thank for the quick reply!  

Yes you can set up a free account you don't have to pay unless you start using their name servers. 

If you need any help testing let me know I have quite a few domains up on their service.  

Thanks again!

**Comment by nik-cole** [comment]
Thanks for the fix! All is good now :+1:

**Comment by dcooney** [comment]
Hi Nik,
Yes, I implemented that fix.

Question - Can you save/update the repeater in your Pantheon environment?
