### ISSUE TITLE
Losing Repeater Template after Plugin-Update

### ISSUE THREAD

**Issue by nklsf** [dcooney/wordpress-ajax-load-more#73]
Hi, 
I love your plugin, however, with every update i lose my custom default repeater-template. 
I get a message

> Warning: fopen(/www/htdocs/w013055e/dailyjoyz.de/wp-content/plugins/ajax-load-more/core/repeater/default.php): failed to open stream: Permission denied in /www/htdocs/w013055e/dailyjoyz.de/wp-content/plugins/ajax-load-more/admin/admin.php on line 66

After that my template is gone. I went to change file permissions on the file and put up my tpl again, but I don't want to hand this to my client this way. (With the fear, that he updates the plugin and breaks the site). 
Any suggestions?

Can you recreate that?

Thanks, 
niklas

**Comment by nklsf** [comment]
update: after i switched file permissions to 777 the old template is back. 
it fetched it from db and put it back up into the default.php, right?
but how can i prevent losing the permissions in the first place?
thanks!

**Comment by dcooney** [comment]
Hi, you shouldn't lose your repeater on update - the idea is when you update the plugin checks the version # in the database with the current plugin version # and if they do not match the default repeater is updated. 

With 777 set on your directory you shouldn't see this happen again.

If you want to test, change the 'ALM_VERSION' in ajax-load-more.php to 1.0 or something smaller than the current.
