### ISSUE TITLE
Feature Request: Query multiple meta fields

### ISSUE THREAD

**Issue by timboozle** [dcooney/wordpress-ajax-load-more#75]
Maybe let the custom_args parameter accept wp's meta_query?

**Comment by dcooney** [comment]
I'm currently developing a system for adding multiple meta queries.
https://www.dropbox.com/s/2n81ji3hqgr8xqy/Screen%20Shot%202015-05-21%20at%209.09.35%20AM.png?dl=0

Do you have an example of how this could be done with the custom_args param?

**Comment by timboozle** [comment]
I take it back :) what you're doing looks good. I created a new parameter but didn't take the relation into account. 

    meta="key:value,key:value"

```
$meta_query_array = explode(",", $meta_query);

foreach ($meta_query_array as $meta) {
	$meta = explode(":", $meta);
	$args['meta_query'][] = array('key' => $meta[0], 'value' => $meta[1]);
}
```

**Comment by ab75173** [comment]
Just looked at the dropbox screen shot and looks good. Any chance there is a way to incorporate meta_query with how the plugin is setup right now? Looking to filter by Location and Topic - both custom fields for a custom post type.
<code>
<?php $term = $_GET['location']; 
$topic = $_GET['topic']; 
$meta_key = $meta_value = '';

        if(isset($_GET['location']) && $_GET['location'] != 'All Locations') {
					$meta_key = 'location,';
					$meta_value = $_GET['location'].',';
				}

	    if(isset($_GET['topic']) && $_GET['topic'] != 'All Topics') {
					$meta_key .= 'topic,';
					$meta_value .= $_GET['topic'].',';
				}

				$meta_key = trim($meta_key,',');
				$meta_value = trim($meta_value,',');
			?>
			<?php echo do_shortcode( '[ajax_load_more post_type="events" repeater="template_3" posts_per_page="4" transition="fade" button_label="Load More" scroll="false" meta_key="'.$meta_key.'" meta_value="'.$meta_value.'"]' ) ?>
</code>
