### ISSUE TITLE
pagination and seo

### ISSUE THREAD

**Issue by natostanco** [dcooney/wordpress-ajax-load-more#76]
Going directly to a url with page/x/ loads up all the content up to the page needed, should it skip previous pages and show only the posts_per_page of the current page? There is content duplication otherwise.

**Comment by dcooney** [comment]
It should load all the posts up to the page requested.
So if you have 6 posts per page and load up page 6, it should load 36 posts.

Where is the content duplication happening? Seems like a bug, but I can't reproduce on my installs.

**Comment by natostanco** [comment]
all right, I saw the [blogpost](http://googlewebmastercentral.blogspot.it/2014/02/infinite-scroll-search-friendly.html) and it says that the way to plugin does it is all right, it just seemed to me a bit weird because higher page numbers can potentially have huge load times, I guess the best option is to limit the infinite scroll to like 10-20 pages and offer the rest without infinite scroll so that only the content of those pages is queried?

There are also some other problems:

- The pagination gets appended to the end of the url after the variables, shouldn't it append before variables? Currently it does it like this `http://exampke.com/?var=Xpage/2/`
- pagination links should be updated as well when the url is, so maybe alm should allow user to specify a id/class for prev and next links to be updated. 

Pagination should also be present in the head but from the scrollsample it is not updated on scrolling instead it preserves the prev/next links of the first time the page was loaded. Also a fallback for noscript is suggested which loads only the posts of the current page as in wordpress default. I do not know if this should be included in alm tough, sure the option which I suggested before to allow scrolling up to X pages would benefit of the fallback functionality,

**Comment by natostanco** [comment]
Actually the way it is implemented on the [example] (http://scrollsample.appspot.com/) loads only the page component of the specified url, than it is possible to scroll towards top to get previous items and towards the bottom to get next items.

**Comment by dcooney** [comment]
That's not the way it works with my plugin.

**Comment by natostanco** [comment]
You mean scrolling toward top? That I guess would require some different js but at least the preloaded module should be able to support loading only the actual page and then scroll to the next ones.

**Comment by dcooney** [comment]
Sorry, that's not the way it works with my plugin.
