### ISSUE TITLE
Multiple taxonomies?

### ISSUE THREAD

**Issue by timichango** [dcooney/wordpress-ajax-load-more#78]
Is there no current way to filter by multiple different taxonomies? Can't find information in the documentation...

Thanks!

**Comment by mihdan** [comment]
Use `custom_args`

**Comment by timichango** [comment]
sorry — any chance you can provide an example of how to add multiple taxonomy filters using custom_args? I'm stumped...

**Comment by mihdan** [comment]
@dcooney?

**Comment by redacherifi** [comment]
An example of "custom_arg" use :
`[ajax_load_more post_type="my_cpt" custom_args="taxonomy1:term1 ; taxonomy2:term2 ; taxonomy2:term3..."]`

> custom_args - A semicolon separated list of value:pair arguments. e.g. tag_slug__and:design,development; event_display:upcoming. Default = null

**Comment by dcooney** [comment]
You can query multiple taxonomies like:

`[ajax_load_more taxonmy="tax_1:tax_2" taxonomy_terms="term_1:term_2" taxonomy_operator="AND"]`
