### ISSUE TITLE
Is there a way to dynamically activate load more button after it was disabled due to reaching last available page 

### ISSUE THREAD

**Issue by responsor** [dcooney/wordpress-ajax-load-more#79]
Is there a way to bring "load more" button to life after the endpage was reached in the inital page load, for example i have alm shortcode with param: custom_query, and i have a javascript that will change that custom_query param in container tag, so after reaching last page for example page 5 (or getting less items that i can diplay on my page with posts_per_page) with first custom_query i click change custom_query button and my js changes it to something new, then i send a request to /wp-admin/admin-ajax.php?action=ajax_load_more_init... and i get something that i then replace my content area with, and i want that "load more" button to come back to life, because while my initial page load had less posts than posts_per_page was set to, my second request with custom_query might have more posts and i would need that button to be able to load the rest of the posts, but when i click on it it just sits still and nothing happens.
Will appreciate any help with this issue.

**Comment by mihdan** [comment]
dcooney, ?
