### ISSUE TITLE
Multiple container classes for different templates

### ISSUE THREAD

**Issue by zamson** [dcooney/wordpress-ajax-load-more#80]
Hi, I really like this plugin and it's pluggable structure how ever I'm missing one vital thing. I bought the whole addon package with custom repeater templates which is great but not being able to change the container classes on a per template basis renders the add on feature almost useless. Is there any way to use different wrappers for different parts of the site?

I don't want to manually change it with css every time since I'm building all my websites on the Foundation 5 framework  which has predefined classes for different types of ul grids etc.

**Comment by dcooney** [comment]
Hi Zamson,
I've actually this to the next release of the plugin. You can still add custom classes on the global settings page, but you will also be able to directly in the shortcode builder.

**Comment by dcooney** [comment]
Hi @zamson, I've added this functionality to ALM v2.7

You can enter custom classes while building a shortcode.
