### ISSUE TITLE
Load More button isn't disabled

### ISSUE THREAD

**Issue by Valonix** [dcooney/wordpress-ajax-load-more#81]
$blog_posts = new WP_Query( array('post_type' => 'post','posts_per_page' => 10 ) );

echo do_shortcode('[ajax_load_more  posts_per_page="10" transition="fade" button_label=""]');

and in the end of all posts button still visible and not have class "done". in category page and taxonomy all fine. This issue only in front-page.php

**Comment by dcooney** [comment]
What does your repeater template look like? 
How many posts are returned?

**Comment by Valonix** [comment]
<article class="singlePost blogHR"> 
<div class="postImg">
<a href="<?php the_permalink();?>">
<?php the_post_thumbnail('full'); ?> 
</a>
</div>
<div class="articleDate "><?php the_time('F j, Y g:i') ?></div>
<div class="data">
<h2 class="entry-title">
<a href="<?php the_permalink();?>"><?php the_title();?></a>
</h2>
<p class="entry-summary"><?php the_excerpt();?></p>
</div>
<div class="blogTags">
<?php the_category(' '); ?>
</div>
</article>
 
I have >100 posts

**Comment by dcooney** [comment]
Does the .done get added after you click it again? Sometimes if the total posts equals the posts per page the button does not add .done until after the next click.

**Comment by Valonix** [comment]
No, I use scroll. One more problem I have duplicated posts.  I need use offset?  With count of value posts per page???

**Comment by Valonix** [comment]
http://blog.looks.fm

**Comment by dcooney** [comment]
set `offset="10"`

**Comment by Valonix** [comment]
ok, but .done not getted

**Comment by Valonix** [comment]
$latest_blog_posts = new WP_Query( array( 'paged' => $paged, 'page' => $paged, 'post_type' => 'post','posts_per_page' => 10 ) );
=======Shortcode===
echo do_shortcode('[ajax_load_more posts_per_page="10" offset="10" transition="fade" button_label=""]');
====ADMIN====
http://savepic.ru/7472042.png

**Comment by Valonix** [comment]
i have http://blog.looks.fm/poleznoe/my-otkryty post with date 09.10.2014 11:11
and i haven`t that in result 
but in result i see last post with date 24.04.2015
