### ISSUE TITLE
Adding Shortcode directly into template

### ISSUE THREAD

**Issue by tsmith0511** [dcooney/wordpress-ajax-load-more#82]
Hi There, 

I'm trying to implement your plugin into my wordpress site but I'm having trouble understanding the process of how to do so. I need the bare minimum functionality--showing 3 posts with a load more button on my general blog page. I created my shortcode but when I paste it directly into my template, the shortcode is outputted. I don't see a php shortcode option and since my posts page is my blog page the only way for me to add the shortcode is through the template. How exactly so I add my shortcode to my blog tempalte file?

I'm also a little confused about how the repeater template comes into play. I only need one, so I'm using the default template and copied the template that loops over each blog post's content. What am I doing wrong?

Thanks for your time and help!

**Comment by dcooney** [comment]
Hi,
To add to a template you would use the following syntax:
`<?php echo do_shortcode('[ajax_load_more button_label="More Posts"]'); ?>`

The repeater template is essentially the content you want repeated.
`<div class="content">
<?php the_title(); ?>
</div>`

**Comment by tsmith0511** [comment]
Ah ok, that's the php shortcode I was looking for. Thank you!

I added the following shortcode to my template file:  
<?php echo do_shortcode('[ajax_load_more post_type="post" offset="1" posts_per_page="1" scroll="false" button_label="Load More"]'); ?>

...however no posts are loaded onto the page, only the load more button. I'm using the default template. Am I still missing something? Thanks

**Comment by dcooney** [comment]
WHat does your repeater look like?

**Comment by tsmith0511** [comment]
I figured it out. I'm using browser-sync with gulp and was not viewing the site on the proxy link.

However, I can't seem to get the category filtering to work. I view pasted issues: [#6](https://github.com/dcooney/wordpress-ajax-load-more/issues/6) but am not sure where to put:
```data-category="<?php echo $cat; ?>```

Here's my repeater template if it's helpful:
```<li<?php if (! has_post_thumbnail() ) { echo ' class="no-img"'; } ?> id="post-<?php the_ID(); ?>" <?php post_class(''); ?>>
	<div class="blog-post-featured-img-wrap">
    	<?php if ( has_post_thumbnail() ) { the_post_thumbnail('', array('class' => 'blog-post-featured-img'));}?>
	</div>
	<div class="blog-post-meta-wrap">
    <div class="blog-post-category"><?php the_category(', ') ?></div>
    		<h4><a href="<?php the_permalink(); ?>" title="<?php the_title(); ?>"><?php the_title(); ?></a></h4>
    		<p class="entry-meta show-for-large-up">
            	<?php get_template_part( 'parts/content', 'byline' ); ?>
    		</p>
    		<a class="btn btn--transparent--red show-for-medium-up" href="<?php the_permalink(); ?>">view post</a>
	</div>
</li>```

And I've put the following shortcode in loop-archive.php, which is called in my archive.php:
```<?php echo do_shortcode('[ajax_load_more post_type="post" offset="1" posts_per_page="3" scroll="false" transition="fade" button_label="Load More"]'); ?>```

Getting the blog posts to filter by category is definitely a function I need. Let me know if you have any clues! Thanks so much for the wonderful plugin.

**Comment by dcooney** [comment]
Hi, please check out the examples section inside the Ajax Load More plugin in your WP Admin.
It has examples for tags, cats and month archives.

**Comment by tsmith0511** [comment]
Hah, the one place I didn't look. Thanks so much!
