### ISSUE TITLE
Feature request: allow repeater template file to be included in theme 

### ISSUE THREAD

**Issue by verticalgrain** [dcooney/wordpress-ajax-load-more#84]
Hi there, 

Thanks for your great work on this awesome plugin - you've done a really solid, thoughtful job on the plugin and it has saved me a lot of time. 

My feature request is to be able to write the repeater template in a php file in the theme, instead of through the plugin admin settings. This way if the theme is used on a different WP install the repeater template will already be included.

**Comment by dcooney** [comment]
Hi @verticalgrain,
I've considered this, but to be honest I haven't been able to come up with a solution that doesn't render my [Custom Repeaters](https://connekthq.com/plugins/ajax-load-more/add-ons/custom-repeaters/) add-on completely obsolete.

**Comment by dcooney** [comment]
Hi @verticalgrain 
I've turned your suggestion into an add-on - (Theme Repeaters)[https://connekthq.com/plugins/ajax-load-more/add-ons/theme-repeaters/]

**Comment by verticalgrain** [comment]
Nice! Thanks for making this, definitely well worth the add-on cost.
