### ISSUE TITLE
Load only on certain pages?

### ISSUE THREAD

**Issue by hayespotter** [dcooney/wordpress-ajax-load-more#87]
Is there a way to make the javascript file only load on pages where I'm using lazy load? I don't want extra javascript loading when it's not needed.

**Comment by dcooney** [comment]
I was actually just researching this yesterday. I don't have it figured out yet, but it's something I want to implement.

**Comment by hayespotter** [comment]
I came up with this solution

function kill_alm() {

	if ( !is_archive() && !is_home() ) {

		add_action( 'wp_print_scripts', 'my_deregister_javascript', 100 );

		function my_deregister_javascript() {
			wp_deregister_script( 'ajax-load-more' );
		}
	}

}

add_action( 'wp', 'kill_alm');

**Comment by dcooney** [comment]
Can't say I agree with the naming of that function!

**Comment by hayespotter** [comment]
Eh, it's a great plugin but it was over stepping its bounds



—
Hayes Potter
9198804368

**Comment by dcooney** [comment]
Closing. ALM JS only loads when the shortcode is present.
