### ISSUE TITLE
Older Posts button + Paging

### ISSUE THREAD

**Issue by mihdan** [dcooney/wordpress-ajax-load-more#88]
How to?

**Comment by dcooney** [comment]
please explain.

**Comment by mihdan** [comment]
I want to see simalteniously on one screen: 1) page-by-page navigation  2) load more.. button
Example - http://www.inmyroom.ru/tags/kukhnya-i-stolovaya

**Comment by mihdan** [comment]
dcooney?

**Comment by dcooney** [comment]
Closing. Not sure what this is referring to.

**Comment by granatmedia** [comment]
http://screenshot.kobzarev.com/2016.11.23-002.jpg

pagination + load more button = together
