### ISSUE TITLE
An AJAX request is a new request to the server

### ISSUE THREAD

**Issue by legomushroom** [dcooney/wordpress-ajax-load-more#90]
Good time of the day!

An AJAX request is a new request to the server, and it is a request to admin-ajax.php. That is not a single post page. Any logic that depends on is_single() or any other page level template tags like it, won't work but some of my functions in repeater template do rely on checks like that. Any workarounds for this right now?

Thanks in advance!

**Comment by codeclinic** [comment]
Your logic is flawed.

admin-ajax.php is to be used purely to pull info -via ajax- via the WordPress core. Therefore it is indipendent of any 'physical' pages. If you need to use 'is_single()' you should reevaluate what you are trying to do and what you need to do to acheive that.
