### ISSUE TITLE
Multiple IDs

### ISSUE THREAD

**Issue by rogerlos** [dcooney/wordpress-ajax-load-more#91]
I'm using ALM for both long lists and multiple short ones, as that allows my clients to have just one tool to learn to insert lists of content on their pages.

When multiple instances of ALM are on one page, they all share the same ID, which is not valid HTML. 

It looks like the only call you make to that in code is line 664 of `ajax-load-more.js`. Is there a reason that cannot be:

```javascript
$.fn.almGetParentContainer = function(){
    return alm.el.closest('.ajax-load-more-wrap'); // Return the parent #ajax-load-more div 
};
```

**Comment by rogerlos** [comment]
Hm, that was the line found here on github, my local version has that at line 851.

**Comment by dcooney** [comment]
Hi,
Yes this is a legacy issue where I cannot remove #ajax-load-more in case other users have styled the container based on this ID.
