### ISSUE TITLE
Preload plugin

### ISSUE THREAD

**Issue by stianjaco** [dcooney/wordpress-ajax-load-more#94]
When I have a category with less posts then the preload amuout variable ("preloaded_amount"), the response is empty. No errors was shown. I found out by changing the ajax url..

**Comment by dcooney** [comment]
That doesn't sound right. 
I'm using preloaded on my blog - https://connekthq.com/blog/

It's set to 5 but I only have 4 posts.
What happens if you removed preloaded? 

Cheers,

**Comment by stianjaco** [comment]
then it shows just perfectly

**Comment by dcooney** [comment]
Weird.
Whats your shortcode?

**Comment by stianjaco** [comment]
[ajax_load_more post_type="post" preloaded="true" preloaded_amount="9" button_label="Last inn flere" repeater="template_1" posts_per_page="9" category="referanser" scroll_distance="30" transition="fade" images_loaded="true"]

**Comment by dcooney** [comment]
Working on my cat pages too - https://connekthq.com/category/ajax-load-more/

Can you share a link?

**Comment by stianjaco** [comment]
ehm, not public. I wrote you an email

**Comment by dcooney** [comment]
When passing filter params you need to reset preloaded="false".
