### ISSUE TITLE
Repeater templates not working correctly

### ISSUE THREAD

**Issue by jorenvh** [dcooney/wordpress-ajax-load-more#97]
Hi,

I'm building a project using your plugin (it's an awesome plugin) now because I needed more repeater templates I bought your add on to have more repeater templates.

I just have one issue let me describe the situation:

I use your plugin on page 1 with the default repeater template (works fine)

I use your plugin on page 2 with repeater: template_2 (works fine for the first record)

When I click the load more button I get my results as expected, BUT for the first record is uses the good template but for all the rest it uses the default one?

I'm looking over something but I can't seem to figure it out. I added a static post title in both repeater templates but only the first one is pulled from the good template.

The short code I use on page 2:

echo do_shortcode('[ajax_load_more repeater="template_2" post_type="post, external_urls, files, infographics, quotes, tweets, videos, audios" taxonomy="stories" taxonomy_terms="'.$scenario->slug.'" posts_per_page="5" scroll="false" transition="fade" images_loaded="false" button_label="Next Page" offset="5" max_pages="100" button_label="Show more" pause="true" scroll_distance="100" pause_override="false"]');

https://wordpress.org/plugins/ajax-load-more/

**Comment by dcooney** [comment]
Cross posting from https://wordpress.org/support/topic/repeater-templates-not-working?replies=11
Closing.
