### ISSUE TITLE
2.8.3 - $.fn.almFilter is not a function

### ISSUE THREAD

**Issue by tomaszrondio** [dcooney/wordpress-ajax-load-more#99]
I just updated to 2.8.3 and it throws an error on filtering. 
Example taken from: https://connekthq.com/plugins/ajax-load-more/examples/filtering/
error:
Uncaught TypeError: $.fn.almFilter is not a function

**Comment by dcooney** [comment]
Not sure what's going on. That function wasn't touched on the update. 
Possible cache issue?

Filtering is still working on the example - https://connekthq.com/plugins/ajax-load-more/examples/filtering/

**Comment by tomaszrondio** [comment]
please close this issue. Somehow js file is not loaded on my instance. Must be some update issue. Will figure it out.

**Comment by xhtmlmaster** [comment]
I get TypeError: $.fn.almFilter is not a function on version 2.8.6 
I did everything exactly like in your example and it is not working.

**Comment by dcooney** [comment]
Can you share a link?

**Comment by magarishor** [comment]
Just replace the " $.fn.almFilter" with "ajaxloadmore.filter". It worked on my end.
https://connekthq.com/plugins/ajax-load-more/docs/public-functions/#filter
